- name: Generate Kubernetes Join Command
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  when: inventory_hostname == 'master'

- name: Save Join Command as Fact
  set_fact:
    join_command: "{{ join_command_raw.stdout }}"
  when: inventory_hostname == 'master'

- name: Distribute Join Command to All Nodes
  set_fact:
    join_command: "{{ hostvars['master'].join_command }}"
  when: inventory_hostname != 'master'

- name: Ensure Master is reachable
  wait_for:
    host: "{{ hostvars['master'].ansible_host }}"
    port: 6443
    timeout: 10
  when: inventory_hostname == 'worker'

- name: Join Worker to Cluster
  shell: "{{ join_command }} >> /home/vagrant/node_joined.log"
  args:
    chdir: /home/vagrant
    creates: /home/vagrant/node_joined.log
  when: inventory_hostname == 'worker'

