# -*- mode: ruby -*-
# vi: set ft=ruby :
NETWORK_PREFIX      = "172.16.16"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.define "v-master" do |master|
    master.vm.network "private_network", type: "dhcp"
    master.vm.hostname = "master"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  config.vm.define "v-worker" do |worker|
    worker.vm.network "private_network", type: "dhcp"
    worker.vm.hostname = "worker"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end
