- name: "[TASK 1] Initialize Kubernetes Cluster"
  shell: kubeadm init --apiserver-advertise-address={{ MASTER_IP }} --pod-network-cidr={{ POD_NETWORK_CIDR }}
  args:
    creates: /etc/kubernetes/admin.conf

- name: "[TASK 2] Set up kubectl for the current user"
  command: "{{ item }}"
  with_items:
    - "mkdir -p $HOME/.kube"
    - "cp /etc/kubernetes/admin.conf $HOME/.kube/config"
    - "chown $(id -u):$(id -g) $HOME/.kube/config"

- name: "[TASK 3] Copy admin.conf to User's kube config"
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
          
- name: "[TASK 4] Generate and save cluster join command"
  hosts: v-master
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: join_command

- name: "[TASK 5] Save join command to file"
  hosts: v-master
  ansible.builtin.copy:
    content: "{{ join_command.stdout }}"
    dest: /joincluster.sh
    mode: '0755'

- name: "[TASK 6] install Pod network"
  shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

