- name: Ensure local kube config directory exists
  delegate_to: localhost
  file:
    path: ~/.kube
    state: directory
    mode: '0755'

- name: Copy kube config from master to local machine
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    flat: yes
  when: inventory_hostname == 'master'

- name: Change ownership of kube config on local machine
  delegate_to: localhost
  file:
    path: ~/.kube/config
    mode: '0600'

- name: Install pip3
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install kubernetes Python client
  ansible.builtin.command:
    cmd: pip3 install kubernetes
    creates: /usr/local/lib/python3.10/dist-packages/kubernetes
- name: Apply Deployment
  kubernetes.core.k8s:
    state: present
    src: "{{ app_path }}/deployment.yml"
  when: inventory_hostname == 'localhost'

- name: Apply HPA
  kubernetes.core.k8s:
    state: present
    src: "{{ app_path }}/hpa.yml"
  when: inventory_hostname == 'localhost'

- name: Apply Ingress
  kubernetes.core.k8s:
    state: present
    src: "{{ app_path }}/ing.yml"
  when: inventory_hostname == 'localhost'

- name: Apply Service
  kubernetes.core.k8s:
    state: present
    src: "{{ app_path }}/svc.yml"
  when: inventory_hostname == 'localhost'

- name: Apply Traffic Generator
  kubernetes.core.k8s:
    state: present
    src: "{{ app_path }}/traffic-generator.yaml"
  when: inventory_hostname == 'localhost'
