- name: Apply Deployment
  kubernetes.core.k8s:
    state: present
    src: "{{ ansible_env.HOME }}/app/deployment.yml"

- name: Apply Traffic Generator
  kubernetes.core.k8s:
    state: present
    src: "{{ ansible_env.HOME }}/app/traffic-generator.yml"

- name: Apply Service
  kubernetes.core.k8s:
    state: present
    src: "{{ ansible_env.HOME }}/app/svc.yml"

- name: Apply Ingress
  kubernetes.core.k8s:
    state: present
    src: "{{ ansible_env.HOME }}/app/ing.yml"

- name: Apply HPA
  kubernetes.core.k8s:
    state: present
    src: "{{ ansible_env.HOME }}/app/hpa.yml"

- name: Check Deployment Status
  ansible.builtin.shell: "kubectl get deployments"
  register: deployment_status

- name: Show Deployment Status
  ansible.builtin.debug:
    msg: "{{ deployment_status.stdout_lines }}"

- name: Check Service Status
  ansible.builtin.shell: "kubectl get svc"
  register: svc_status

- name: Show Service Status
  ansible.builtin.debug:
    msg: "{{ svc_status.stdout_lines }}"

- name: Check Ingress Status
  ansible.builtin.shell: "kubectl get ing"
  register: ing_status

- name: Show Ingress Status
  ansible.builtin.debug:
    msg: "{{ ing_status.stdout_lines }}"
