---
- name: init k8s
  hosts: k8s-nodes
  become: yes
  vars:
    MASTER_IP: "192.168.56.14"
    POD_NETWORK_CIDR: "192.168.0.0/16"
    app_path: "{{ ansible_env.HOME }}/Practice/app"

  roles:
     - { role: k8s-installation, tags: ['k8s-installation'] }
     - { role: k8s-init, tags: ['k8s-init'] }
     - { role: k8s-join, tags: ['k8s-join'] }
     - { role: k8s-monitoring, tags: ['k8s-monitoring'] }

  handlers:
   - name: Restart containerd
     ansible.builtin.systemd:
       name: containerd
       state: restarted
       enabled: yes
  
   - name: Load Kernel Modules
     ansible.builtin.shell: |
       modprobe overlay
       modprobe br_netfilter
  
   - name: Apply sysctl settings
     ansible.builtin.command: sysctl --system >/dev/null 2>&1
