- name: initialize the cluster
  shell: kubeadm init --apiserver-advertise-address=192.168.56.12 --apiserver-cert-extra-sans=192.168.56.12 --pod-network-cidr=192.168.0.0/16

- name: create .kube dir
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Ensure .kube dir exists
  file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    mode: 0755

- name: Check if kube config exists
  stat:
    path: /home/vagrant/.kube/config
  register: kube_config

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
  when: not kube_config.stat.exists

- name: install Pod network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
